language: ruby

before_install:
  - gem install bundler

install:
  - travis_retry sudo apt-get install fsharp
  - travis_retry bundle install

script:
  - bundle exec rake

rvm:
 - 2.3.1

branches:
  only: master

notifications:
  email: henrik@haf.se

gemfile: Gemfile
